// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package p11

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type V11Msg struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Crc32                uint32   `protobuf:"varint,2,opt,name=crc32,proto3" json:"crc32,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *V11Msg) Reset()         { *m = V11Msg{} }
func (m *V11Msg) String() string { return proto.CompactTextString(m) }
func (*V11Msg) ProtoMessage()    {}
func (*V11Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *V11Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_V11Msg.Unmarshal(m, b)
}
func (m *V11Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_V11Msg.Marshal(b, m, deterministic)
}
func (m *V11Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_V11Msg.Merge(m, src)
}
func (m *V11Msg) XXX_Size() int {
	return xxx_messageInfo_V11Msg.Size(m)
}
func (m *V11Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_V11Msg.DiscardUnknown(m)
}

var xxx_messageInfo_V11Msg proto.InternalMessageInfo

func (m *V11Msg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *V11Msg) GetCrc32() uint32 {
	if m != nil {
		return m.Crc32
	}
	return 0
}

func (m *V11Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*V11Msg)(nil), "p11.V11Msg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x30, 0x34, 0x54, 0xf2, 0xe1, 0x62, 0x0b, 0x33,
	0x34, 0xf4, 0x2d, 0x4e, 0x17, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0d, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x93, 0x8b, 0x92, 0x8d, 0x8d, 0x24, 0x98,
	0xc0, 0x82, 0x10, 0x8e, 0x90, 0x04, 0x17, 0x7b, 0x41, 0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a, 0x04,
	0xb3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0x9b, 0xc4, 0x06, 0x36, 0xd9, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x0e, 0x79, 0x35, 0x5f, 0x66, 0x00, 0x00, 0x00,
}
